# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "tts-unstable-${version}";
  version = "2018-02-16";

  goPackagePath = "github.com/peterzky/tts";

  src = fetchgit {
    url = "https://github.com/peterzky/tts.git";
    rev = "b4fd5f9c8e0a70019a32997554756453f5e543a5";
    sha256 = "049pbqp91481g3fgwv4k6lgixdj4m4s7hbd2ffyz7b5j67c3iq6f";
  };

  goDeps = ./deps.nix;

  meta = { description = "text-to-speech client use AWS"; };
}
