# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "9365c0c6f32778b59eb41491629d37721658efb8";
      sha256 = "058c86vzmvnz9b5v2zxs5a3847iszss74k0xpmn8zg70l9hx11pl";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://github.com/golang/net.git";
      rev = "6a8eb5e2b1816b30aa88d7e3ecf9eb7c4559d9e6";
      sha256 = "1aqnygfvz2sla1qkq0vakxm1lhfq1dayr0zvnpck1j5zdiby66jw";
    };
  }
]
