# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "timer-unstable-${version}";
  version = "2018-12-22";

  goPackagePath = "github.com/peterzky/timer";

  src = fetchgit {
    url = "https://github.com/peterzky/timer";
    sha256 = "07qnsikyjnhanmzxc9vvsz2j9kb0iympq6f1khjzggs361gfvl17";
    rev = "bd00a14ffc6fc891b0041f56a73979da065cb036";
    # date = 2018-12-22T17:56:10+08:00;
  };

  postInstall = ''
    cp -av $src/sound/ $bin/
  '';

  meta = { description = "timer written in go for personal usage"; };
}
